### PR TITLE
finished cypress tests. minimum amount of tests working.

### PR DESCRIPTION
**Pull request by emt1999**
Co-Authored-By: niknagarajan <91632385+niknagarajan@users.noreply.github.com>

### CODE REVIEW

**Comment by emt1999** [comment]
confirming @niknagarajan

**Comment by ccrister** [comment]
LGTM!

**Comment by niknagarajan** [comment]
all tests passing

**Comment by rcereno** [comment]
tests look great! since only minimum amount, may need to add more but current version looks great so far! good job!

**Pull request merged**
