### PR TITLE
Frontend rhoyal

### PR DESCRIPTION
**Pull request by rcereno**
Code Review from Code Author Rhoyalinn

### CODE REVIEW

**Comment by emt1999** [comment]
too many conflicts, there is a better version

**Comment by ccrister** [comment]
LGTM!

**Comment by niknagarajan** [comment]
Clean code but too many merge conflicts occurring

**Comment by rcereno** [comment]
closing issue due to taking suggestions from comments by not merging with main due to many merge conflicts with the main code as many changes have been been since this PR has been submitted.

**Pull request closed without merging**
